# Generated by Django 5.1.1 on 2024-09-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
