# Generated by Django 5.1.1 on 2024-09-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='File',
        ),
    ]
